version: '3.8'
services:
    mongodb:
        image : nertworkweb/mongodb-no-avx:latest
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongodb/database:/data/db
        ports:
            - 27017:27017
        networks:
            - next-express-net
networks:
    next-express-net:
        driver: bridge